### ISSUE TITLE
Make CI for uploading built website

### ISSUE THREAD

**Issue by Devnol** [neutrontechnologies/neutrontechnologies.github.io#12]
Write a Continuous Integration workflow that builds react code from master and pushes it to gh-pages

**Comment by Midou36O** [comment]
seems to be a good opportunity to use your server for that

**Comment by Devnol** [comment]
Not really, it'd be much faster and much more efficient to run it on Actions.

**Comment by Midou36O** [comment]
i'm not really experienced on github actions so someone else should do it

**Comment by Devnol** [comment]
I'm gonna do it. It's just a simple yaml file.

**Comment by Odyssey346** [comment]
"simple"
ahhhhhhhhhhhhhhhhhhhhhhhahahahahaahahaha

i could not figure out github actions at all. it's confusing as all hell

**Comment by Midou36O** [comment]
He's probably more experienced than you in that domain so we should let him do it.

**Comment by Devnol** [comment]
It's just YAML syntax. Plus, you don't have to do it yourself there's examples in the marketplace. But for now, I'm gonna do it.

**Comment by Odyssey346** [comment]
i agree with midou let devnol do this

**Comment by Devnol** [comment]
Yeet I actually finished a feature in less than 24 hours I am impressed with myself
