### ISSUE TITLE
Add a login page for the team (server access, docker, etc..)

### ISSUE THREAD

**Issue by Midou36O** [neutrontechnologies/neutrontechnologies.github.io#9]
Self explanatory

**Comment by Odyssey346** [comment]
What does this have to do with this site?

**Comment by Odyssey346** [comment]
I guess you mean something with the **domain**

**Comment by Midou36O** [comment]
no i actually mean some buttons to redirect to dev side stuff

**Comment by Midou36O** [comment]
Since Devnol Resigned, we do not have any server, so it will be Scrapped.
